name: Release (manual)
on:
  workflow_dispatch:
    inputs:
      releaseAs:
        description: "Тип релізу (auto|patch|minor|major)"
        required: true
        default: "auto"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - name: Git identity
        run: |
          git config user.name "onestat-release-bot"
          git config user.email "release-bot@users.noreply.github.com"
      - name: Run standard-version
        if: github.ref_name == 'master'
        run: |
          case "${{ github.event.inputs.releaseAs }}" in
            auto) npx standard-version ;;
            patch) npx standard-version --release-as patch ;;
            minor) npx standard-version --release-as minor ;;
            major) npx standard-version --release-as major ;;
          esac
      - name: Push commit and tags
        if: github.ref_name == 'master'
        run: git push --follow-tags origin HEAD:master
